import TodosTable from '@/components/todosTable/TodosTable';
import { Inter } from '@next/font/google';
import Head from 'next/head';
const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <section className='text-3xl text-gray-700 font-bold mb-5'>
        <TodosTable></TodosTable>

        </section>
      </main>
    </>
  )
}
